import SiteHeader from "../components/SiteHeader"
import SiteFooter from "../components/SiteFooter"
import BottomTabBar from "../components/BottomTabBar"

function AboutPage() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-950 text-gray-900 dark:text-white flex flex-col font-mono">
      <SiteHeader />

      <main className="max-w-2xl mx-auto px-4 py-12 flex-1 w-full pb-20 md:pb-12">
        <p className="text-xs uppercase tracking-[5px] text-red-500 mb-3">About</p>
        <h1 className="text-3xl font-black uppercase tracking-wide mb-2">Built for Dota 2 Fans</h1>
        <p className="text-sm uppercase tracking-widest text-gray-500 dark:text-gray-600 mb-12 pb-12 border-b border-gray-200 dark:border-gray-800">
          Free · No login required · Tier 1 only
        </p>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">The Problem</p>
          <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed mb-3">
            Watching pro Dota 2 matches after the fact is frustrating. Tournament streams run for 6 to 8 hours covering multiple games. Finding the specific match you want means scrubbing through hours of content, guessing timestamps, and often landing in the wrong game entirely.
          </p>
          <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
            There was no easy way to jump directly to a specific match — until now.
          </p>
        </section>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">What Spectate Esports Does</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { title: "Timestamped VODs + Series Highlights", desc: "Direct Twitch links that jump to the exact moment a match begins. No scrubbing. When an official YouTube highlight reel exists for the series, a Series Highlights link appears alongside the VOD — one click for the full replay, one click for the 10-minute recap. Both hidden in spoiler-free mode." },
              { title: "Streams in Your Language", desc: "Below the main replay button, every other broadcast recorded for that game is listed by language — official regional streams and community co-streams alike, each labeled EN, RU, ES and so on. Streams with a resolved replay jump straight to the game start; the rest link to the broadcaster's channel and say so. The official English broadcast always stays the default." },
              { title: "Draft Breakdown", desc: "Full hero picks with portrait icons, pro player names, KDA stats, and rampage attribution for every game. A highlighted orange border marks any player who scored a rampage (5-kill streak). Bans are listed below by team. Hidden in spoiler-free mode." },
              { title: "End-Game Stats", desc: "See the full economic picture for every completed game: a gold advantage graph you can scrub through minute by minute — hover anywhere on desktop or drag your finger horizontally on mobile to see exactly who was ahead and by how much at any point. Roshan kills, rapier purchases, rampages, and team fights appear as icon markers directly on the gold line — colored by the team that triggered the event so a Dire Roshan in Radiant's lead band stands out in red. Team fight markers show the winning side, deaths, and net gold swing. Hover any marker on desktop to see details; on mobile, tap once for the tooltip, tap again to jump to that moment in the VOD. Also shows final networth, complete item builds including neutral items, and a proportional networth bar for each player. Hover any item to see its name and a link to the Dota 2 Wiki. First blood time and Roshan kill count appear below the game score. Automatically loaded when you open any match details panel. Hidden in spoiler-free mode." },
              { title: "AI Match Summaries", desc: "Draft analysis, strategy breakdown, MVP, and match highlights — generated by Claude." },
              { title: "Series Grouping", desc: "Games are grouped into BO1, BO3, and BO5 series with series scores. When viewing a game, a G1/G2/G3 switcher appears in the panel header showing each game's winner (e.g. G2 Nigma Galaxy) so you can jump between games without closing the panel. Winner names are hidden in spoiler-free mode." },
              { title: "Spoiler-Free Mode", desc: "On by default for new visitors, so scores, results, KDA stats, series length, and format labels stay hidden until you choose to reveal them. Reveal any single match from its details panel, or turn all scores on from the header or Settings. Your choice is remembered across visits." },
              { title: "Shareable Match Cards", desc: "Every match has a unique link with a rich preview card. Share a specific game directly." },
              { title: "Live Series Companion", desc: "See the full story of an in-progress series without waiting for it to finish. Click any live match row with a score to open a companion panel: a G1/G2/... switcher lets you jump between each completed game and the game currently being played, one at a time, instead of scrolling past everything at once — it opens on whichever game is live. Each completed game shows its winner, kill score, notable-event badges (Rampage, Divine Rapier, big gold swings, mega-creep comebacks), duration, and the full 5v5 draft — tap any game to jump straight into its complete stats, gold graph, and VOD. The game currently being played shows an interactive live net-worth graph you can scrub back through to see how the lead was built, a momentum read of who is ahead, the live kill score, and the full live draft with hero and player names, all updating automatically while you watch. Watch links for the live game sit right at the top - the official Twitch and YouTube broadcasts, plus every other-language or co-stream link we know about - so you can start watching without leaving the panel. The bracket round (e.g. Upper Bracket Final, Grand Final) is shown at the top. When multiple matches are live simultaneously, a count is shown at a glance." },
              { title: "Tournament Hub", desc: "Tap any tournament name in the feed to expand its full details inline — standings, bracket tree, highlights, and hero pick/ban stats without leaving the homepage. Works for live, upcoming, and recently completed events. The Stage tab is format-aware: group stages show W/L standings above round-by-round match results; playoff stages show the full elimination bracket. Switch between Group Stage and Playoffs with the stage picker." },
              { title: "Hero Pick/Ban Stats", desc: "See which heroes are being picked and banned most across a tournament, with win rates and contested counts. Shows top 25 by default with a button to reveal all." },
              { title: "Tournament Player Leaderboard", desc: "Inside the Stats tab of the Tournament Hub, switch to Players to see which players performed best across the tournament. Five leaderboards: kills, deaths, assists, net worth, and GPM — each showing the top 5 with rank, hero played, team, games played, and stat value. Games played is shown next to each name so you can put totals in context. Click any row to open that specific match." },
              { title: "My Teams", desc: "Follow your favorite teams and get a personalized feed of their matches. Open My Teams anytime from Settings (More tab on mobile), or via the Manage button on the My Teams card at the top of the feed. Search for any Tier 1 team and add them instantly — including by nickname (e.g. \"boomboys\" finds BetBoom Team) — remove teams with one tap, and toggle live match alerts on or off without changing your team list. The card stays visible even on days your teams aren't playing, showing their next scheduled match. After enabling alerts, use Send test notification to confirm delivery on your device. Follow/unfollow stars appear in the match details panel next to each team name. Followed-team rows are highlighted in amber throughout the feed. Saved in your browser, no account needed. Push notifications update automatically when you add or remove teams." },
              { title: "Tournament Pages", desc: "Dedicated pages for Tier 1 series at /tournaments. See live, upcoming, and completed events with prize pools, dates, full team rosters by region, player names with nationality flags, stage timelines, and per-stage standings. Each stage card shows the match format (Round Robin, BO1/BO3/BO5) and a color-coded advancement ladder — who goes to Upper Bracket, Last Chance, or gets eliminated — so you always know what's at stake. Includes an AI-generated summary for each event." },
              { title: "Search Suggestions", desc: "The search bar shows smart suggestions as you type. Start typing a hero name, team name, or tournament and a live dropdown appears instantly — all matching is local with no API calls, so results show on every keystroke. Hero suggestions navigate directly to that hero's match history page. Team and tournament suggestions run the match filter. When nothing is typed yet, contextual chips appear instead: the live tournament if one is running, winning teams from recent matches, and your last 5 searches (removable). Keyboard navigable: arrow keys move through suggestions, Enter selects." },
              { title: "Game Indicators", desc: "Each series card and match details panel shows icon badges for notable in-game events, displayed next to the team they belong to. A sword icon marks the team that had Divine Rapier. A chart icon marks the team that recovered from a 20,000+ gold deficit. A lightning bolt marks the team that won despite having mega creeps against them. A skull icon marks any team with a player who scored a rampage (5-kill streak). Hidden in spoiler-free mode." },
              { title: "Playoff Stage Labels", desc: "Bracket stage labels (Grand Final, Upper Bracket Final, Semifinal, and so on) now appear on completed match rows just like they do on live and upcoming matches. Grand Final cards also get a distinct gold border, warm background, and trophy badge so championship matches stand out at a glance." },
              { title: "Tier 1 Filter", desc: "The homepage shows only matches from top-tier tournaments. Events are filtered using PandaScore tier S and A classifications - the same tier system used for live and upcoming matches - so the feed stays clean and focused on high-quality pro play." },
              { title: "Calendar Feeds", desc: "Subscribe to Dota 2 match schedules in Google Calendar, Apple Calendar, or Outlook with one click — no copy-pasting URLs. Add buttons appear in the Tournament Hub (for all tournaments or a specific one), in the My Teams section after following a team, and in Settings. The All Tournaments feed covers every active and upcoming pro tournament in one URL; a team-specific feed is available at /calendar." },
              { title: "Install as App", desc: "Add Spectate Esports to your home screen on iPhone or Android. Once installed, the site launches full-screen with no browser bar and works offline using cached data from your last visit. No app store needed. Tap Settings (or More on mobile) then Install as app - on iPhone Safari a 3-step visual guide walks you through the Share button and Add to Home Screen; on Android it triggers the native install dialog." },
              { title: "Tournament Highlights", desc: "Official YouTube highlight videos for the active tournament, surfaced in the Highlights tab of the Tournament Hub. A thumbnail grid shows recent clips from ESL, PGL, BLAST, WePlay, Esports World Cup, and Valve's Dota 2 channel. Click any card to watch inline without leaving the page. Thumbnails are blurred in spoiler-free mode." },
              { title: "Dota 2 News Feed", desc: "Headlines and excerpts pulled from four sources simultaneously: Valve's official Steam announcements, the Steam News API (which aggregates third-party Dota coverage), Liquipedia for roster moves and transfers, and Currents API for editorial coverage. Covers patch notes, roster moves, tournament news, and match results within hours of publication. All articles link directly to the original source - no AI-generated summaries, no paraphrasing. A small indicator dot appears on the News tab and header link when new articles have been published since your last visit." },
              { title: "Dota 2 Glossary", desc: "Definitions for 25 core Dota 2 concepts at /glossary — from Draft and GPM to Roshan, Rampage, Divine Rapier, and Mega Creeps. Each term has a short definition and a full explanation. Designed for viewers new to pro Dota 2 who want to understand the vocabulary used in match commentary and AI summaries." },
              { title: "Team Organization Pages", desc: "Dedicated pages for each Tier 1 organization at /teams — OG, Team Spirit, Gaimin Gladiators, Tundra Esports, Team Liquid, Evil Geniuses, and more. Each page covers the org's competitive region, historical TI championship record, and org background. Player rosters change frequently so they are not listed here — each page links directly to the org's Liquipedia page for the current lineup." },
              { title: "Pro Player Profiles", desc: "Career profiles for 28 elite Tier 1 Dota 2 players at /players — TI champions, iconic legends, and top-tier talent spanning every era of professional Dota. Each page covers TI championship history, role, nationality, and career highlights. Profiles focus on immutable career facts only; current team affiliations change too frequently to maintain here, so each profile links directly to the player's Liquipedia page for the current lineup." },
              { title: "The International History", desc: "Complete history of The International at /tournaments/the-international — all 14 editions from TI1 (2011) through TI14 (2025). Champions, runners-up, prize pools, and host cities for every edition. Includes a breakdown of multi-year champions (OG 2x, Team Spirit 2x, Team Liquid 2x) and the historical context of the crowd-funded prize pool era (TI4–TI12)." },
              { title: "Hero Search", desc: "Search for any Dota 2 hero by name to see every tier-1 match in which they were picked. Type \"Puck\" or \"Anti-Mage\" in the search bar and you go straight to that hero's page at /heroes/{slug} — showing all professional matches with teams, tournament, date, and whether Radiant or Dire won. Results load 100 at a time, newest first, with a Load more button to go further back. Data sourced from OpenDota. Bans are excluded — picks only." },
              { title: "Unified Match Feed", desc: "The homepage shows live, just ended, upcoming, and completed matches in a single sorted list of tournament cards. Each tournament appears once - all match states are inside the same card, separated by labeled dividers when multiple states are present. Live tournaments sort to the top. Followed-team matches surface at the top of their card with an amber highlight. A sticky live banner appears at the top when matches are in progress. Search is a full-screen overlay opened from the magnifier icon in the header. When search results are showing, a Load more matches button appears at the bottom to browse deeper into match history — it automatically keeps fetching until at least one new match for your query appears." },
              { title: "Browse Results by Date", desc: "A date strip above the feed lets you navigate between days. The strip shows the previous day, the selected day, and every future day that has matches scheduled — Today, Tomorrow, May 24, May 25, and so on. Tap the previous day to step back and the strip slides with you. Results are grouped by tournament with a collapsible section per event." },
              { title: "Just Ended", desc: "Series results appear in the feed within about a minute of the last game finishing — pulled directly from PandaScore before OpenDota has indexed the match. You see team names, series score, tournament, and bracket round immediately. Replay links and draft data fill in automatically once OpenDota catches up, then the entry moves into the regular results feed." },
              { title: "Editorial Coverage", desc: "Original articles covering major tournaments — one per day during events like BLAST Slam VII and DreamLeague. Team analysis, storyline breakdowns, match previews, and daily narratives written to give context to what you're watching. The latest story appears as a card in the homepage feed during active coverage. Each article has a share button: native share sheet on mobile, or X and Copy link on desktop. All articles at /articles." },
              { title: "Feedback", desc: "A feedback button in the bottom-right corner of every page. Share a bug report, feature idea, or anything on your mind directly with the team. No account required." },
            ].map(f => (
              <div key={f.title} className="border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900/40 p-4 rounded">
                <p className="text-xs font-bold uppercase tracking-[3px] text-gray-900 dark:text-white mb-1.5">{f.title}</p>
                <p className="text-xs text-gray-500 dark:text-gray-500 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">Tournaments Covered</p>
          <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed mb-4">Spectate Esports filters to Tier 1 tournaments only — no amateur or regional leagues.</p>
          <div className="flex flex-wrap gap-2">
            {["DreamLeague", "ESL One", "PGL", "BLAST", "WePlay", "Riyadh Masters", "The International", "Beyond The Summit"].map(t => (
              <span key={t} className="text-xs uppercase tracking-widest px-3 py-1.5 border border-gray-200 dark:border-gray-800 text-gray-500 dark:text-gray-600 rounded-sm">{t}</span>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">Frequently Asked Questions</p>
          <div className="divide-y divide-gray-200 dark:divide-gray-800">
            {[
              { q: "How do I find a match VOD?", a: "Search for a team name or tournament on the homepage. Click any past match to open the details panel and get a direct Twitch link timestamped to that exact game." },
              { q: "How far back do VODs go?", a: "Twitch VODs are available for up to 60 days. Matches older than that will show no VOD found." },
              { q: "Why are multiple stream links shown?", a: "For most matches, only the single assigned sub-channel is shown. In rare cases where PandaScore has not yet assigned a specific channel to a match, all active streams for that tournament are shown as fallback options." },
              { q: "What is the AI match summary?", a: "Each match has an AI-generated summary covering draft analysis with a draft winner, team strategy, MVP, and a match highlight. Generated using Claude by Anthropic." },
              { q: "Can I share a specific match?", a: "Yes. Click the share button in any match drawer to copy a direct link. The link includes a preview card showing teams, score, and tournament." },
              { q: "What is spoiler-free mode?", a: "Spoiler-free mode hides scores, results, KDA stats, series game count, and format labels (BO3/BO5), so nothing reveals the outcome or length of a series before you watch. It is on by default for new visitors. Use the toggle in the header or Settings to show all scores anytime, or reveal a single match from its details panel. Your preference is saved across sessions." },
              { q: "Is Spectate Esports free?", a: "Yes. Spectate Esports is completely free with no account required." },
              { q: "How does My Teams work?", a: "Open any match in the details panel and tap the star next to a team name to follow them. You can also open the Manage Teams sheet to search for any Tier 1 team and add or remove teams from one place. A My Teams card appears at the top of the date feed showing all their live, upcoming, and completed matches. Your followed teams are saved in your browser - no login required. They will not carry over to other browsers, incognito mode, or other devices." },
              { q: "How do I see what happened earlier in a live series?", a: "Click the live match row for that series - a companion panel opens with a G1/G2/... switcher so you can flip between each finished game's draft, kill score, notable-event badges, and duration, and the live game's net-worth graph, momentum read, and live draft. Tap any finished game to open its full stats, gold graph, and VOD." },
              { q: "Which data sources are used?", a: "Match data from OpenDota API. Live and upcoming matches from PandaScore. VOD links from the Twitch API. AI summaries from Anthropic Claude." },
              { q: "What are the tournament detail pages?", a: "Visit /tournaments to see all current and upcoming Tier 1 Dota 2 events. Click any event to see its full team roster (with player names and nationality flags), stage breakdown (Group Stage, Playoffs), standings tables, and an AI-generated event summary." },
              { q: "How do calendar feeds work?", a: "Click any \"Add to Calendar\" button — in the Tournament Hub, the My Teams section, or Settings — and choose Google Calendar, Apple Calendar, or Outlook. One click opens the subscribe flow in your calendar app directly, no URL copying needed. The feed auto-updates as new matches are scheduled (group stages, playoffs, new events). Google Calendar refreshes every 12-24 hours; Apple Calendar can refresh as often as every 5 minutes. For more options, visit /calendar to build a team-specific feed." },
              { q: "How do push notifications work?", a: "Follow at least one team, then turn on alerts from Settings, or from the Manage button on your My Teams card. We'll explain what you're signing up for before your browser asks for permission, so nothing surprises you. You'll get an alert a few minutes before a followed team's match starts, so you don't miss the draft, another when it goes live, and one when the replay is ready if you missed it. Tapping a notification takes you straight to the match (replays open spoiler-free). The full controls live in both Settings and My Teams: tap \"Customize alerts\" to turn any of the three alert types off individually, or set quiet hours so nothing pings you during the window you choose. On Android, this works in Chrome with or without the app installed. On iPhone and iPad, you must first install the app to your home screen via Safari; if you haven't, My Teams shows an \"Add to Home Screen\" button that walks you through it. iOS restricts push notifications to installed PWAs only." },
            ].map(({ q, a }) => (
              <div key={q} className="py-5">
                <p className="text-xs font-bold uppercase tracking-widest text-gray-900 dark:text-white mb-2">{q}</p>
                <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </section>

        <div className="pt-12 border-t border-gray-200 dark:border-gray-800 text-center">
          <p className="text-xs uppercase tracking-[5px] text-gray-500 dark:text-gray-600 mb-4">Ready to watch?</p>
          <a href="/" className="inline-block px-8 py-3.5 bg-red-600 hover:bg-red-700 text-white text-xs font-bold uppercase tracking-[4px] rounded transition-colors">
            Find a Match
          </a>
        </div>
      </main>

      <SiteFooter />
      <BottomTabBar />
    </div>
  )
}

export default AboutPage
