import SiteHeader from "../components/SiteHeader"

function AboutPage() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-950 text-gray-900 dark:text-white flex flex-col font-mono">
      <SiteHeader />

      <main className="max-w-2xl mx-auto px-4 py-12 flex-1 w-full">
        <p className="text-xs uppercase tracking-[5px] text-red-500 mb-3">About</p>
        <h1 className="text-3xl font-black uppercase tracking-wide mb-2">Built for Dota 2 Fans</h1>
        <p className="text-sm uppercase tracking-widest text-gray-500 dark:text-gray-600 mb-12 pb-12 border-b border-gray-200 dark:border-gray-800">
          Free · No login required · Tier 1 only
        </p>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">The Problem</p>
          <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed mb-3">
            Watching pro Dota 2 matches after the fact is frustrating. Tournament streams run for 6 to 8 hours covering multiple games. Finding the specific match you want means scrubbing through hours of content, guessing timestamps, and often landing in the wrong game entirely.
          </p>
          <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
            There was no easy way to jump directly to a specific match — until now.
          </p>
        </section>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">What Spectate Esports Does</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { title: "Timestamped VODs", desc: "Direct Twitch links that jump to the exact moment a match begins. No scrubbing." },
              { title: "Draft Breakdown", desc: "Full hero picks and bans with pro player names and KDA stats for every game." },
              { title: "AI Match Summaries", desc: "Draft analysis, strategy breakdown, MVP, and match highlights — generated by Claude." },
              { title: "Series Grouping", desc: "Games are grouped into BO1, BO3, and BO5 series with series scores." },
              { title: "Spoiler-Free Mode", desc: "Hide scores and match results until you're ready to reveal them. Toggle on/off anytime." },
              { title: "Shareable Match Cards", desc: "Every match has a unique link with a rich preview card. Share a specific game directly." },
              { title: "Live Match Scores", desc: "See live series scores, current game, and completed game results while matches are in progress." },
              { title: "Tournament Hub", desc: "Group stage standings, round schedule, and format info (Swiss, Double Elimination) for the active tournament." },
              { title: "Hero Pick/Ban Stats", desc: "See which heroes are being picked and banned most across a tournament, with win rates and contested counts." },
              { title: "Draft X Posts", desc: "Generate ready-to-post X/Twitter content for every game in a completed series, with a downloadable series result image." },
            ].map(f => (
              <div key={f.title} className="border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900/40 p-4 rounded">
                <p className="text-xs font-bold uppercase tracking-[3px] text-gray-900 dark:text-white mb-1.5">{f.title}</p>
                <p className="text-xs text-gray-500 dark:text-gray-500 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">Tournaments Covered</p>
          <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed mb-4">Spectate Esports filters to Tier 1 tournaments only — no amateur or regional leagues.</p>
          <div className="flex flex-wrap gap-2">
            {["DreamLeague", "ESL One", "PGL", "BLAST", "WePlay", "Riyadh Masters", "The International", "Beyond The Summit"].map(t => (
              <span key={t} className="text-xs uppercase tracking-widest px-3 py-1.5 border border-gray-200 dark:border-gray-800 text-gray-500 dark:text-gray-600 rounded-sm">{t}</span>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <p className="text-xs uppercase tracking-[4px] text-red-500 mb-4">Frequently Asked Questions</p>
          <div className="divide-y divide-gray-200 dark:divide-gray-800">
            {[
              { q: "How do I find a match VOD?", a: "Search for a team name or tournament on the homepage. Click any past match to open the details panel and get a direct Twitch link timestamped to that exact game." },
              { q: "How far back do VODs go?", a: "Twitch VODs are available for up to 60 days. Matches older than that will show no VOD found." },
              { q: "Why are multiple stream links shown?", a: "When tournaments run concurrent matches on different sub-channels, all matching streams are shown. This is a known limitation — Twitch does not expose which stream carried which match." },
              { q: "What is the AI match summary?", a: "Each match has an AI-generated summary covering draft analysis with a draft winner, team strategy, MVP, and a match highlight. Generated using Claude by Anthropic." },
              { q: "Can I share a specific match?", a: "Yes. Click the share button in any match drawer to copy a direct link. The link includes a preview card showing teams, score, and tournament." },
              { q: "What is spoiler-free mode?", a: "Toggle \"Spoilers: Off\" in the header to hide all scores and match results. Your preference is saved across sessions." },
              { q: "Is Spectate Esports free?", a: "Yes. Spectate Esports is completely free with no account required." },
              { q: "Which data sources are used?", a: "Match data from OpenDota API. Live and upcoming matches from PandaScore. VOD links from the Twitch API. AI summaries from Anthropic Claude." },
            ].map(({ q, a }) => (
              <div key={q} className="py-5">
                <p className="text-xs font-bold uppercase tracking-widest text-gray-900 dark:text-white mb-2">{q}</p>
                <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </section>

        <div className="pt-12 border-t border-gray-200 dark:border-gray-800 text-center">
          <p className="text-xs uppercase tracking-[5px] text-gray-500 dark:text-gray-600 mb-4">Ready to watch?</p>
          <a href="/" className="inline-block px-8 py-3.5 bg-red-600 hover:bg-red-700 text-white text-xs font-bold uppercase tracking-[4px] rounded transition-colors">
            Find a Match
          </a>
        </div>
      </main>

      <footer className="border-t border-gray-200 dark:border-gray-800 px-4 py-4 text-center text-xs uppercase tracking-widest text-gray-500 dark:text-gray-600">
        Spectate Esports · Powered by OpenDota + Twitch · spectateesports.live
      </footer>
    </div>
  )
}

export default AboutPage
